--liquibase formatted sql

--changeset subhajitsaha:1587742146046-1
CREATE TABLE student (id INTEGER NOT NULL, name VARCHAR(50) NOT NULL, active BOOLEAN DEFAULT TRUE, CONSTRAINT student_pkey PRIMARY KEY (id));

--changeset subhajitsaha:1587742146046-2
CREATE TABLE product (_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, description VARCHAR(255), image_url VARCHAR(255), price numeric(19, 2), CONSTRAINT product_pkey PRIMARY KEY (_id));

--changeset subhajitsaha:1587742146046-3
CREATE TABLE parent (id INTEGER NOT NULL, name VARCHAR(50) NOT NULL, active BOOLEAN DEFAULT TRUE, CONSTRAINT parent_pkey PRIMARY KEY (id));

--changeset subhajitsaha:1587742146046-4
CREATE TABLE department (id INTEGER NOT NULL, name VARCHAR(50) NOT NULL, active BOOLEAN DEFAULT TRUE, CONSTRAINT department_pkey PRIMARY KEY (id));

--changeset subhajitsaha:1587742146046-5
CREATE TABLE teacher (id INTEGER NOT NULL, name VARCHAR(50) NOT NULL, active BOOLEAN DEFAULT TRUE, CONSTRAINT teacher_pkey PRIMARY KEY (id));

